"""add topics and monthly reports

Revision ID: 273b04b83b29
Revises: ace033cab559
Create Date: 2026-04-06 12:51:03.999339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273b04b83b29'
down_revision: Union[str, Sequence[str], None] = 'ace033cab559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_topics_id'), 'research_topics', ['id'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('doi_list', sa.String(length=500), nullable=True),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('nir_score', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('additional_score', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('total_score', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'period_year', 'period_month', name='_user_topic_period_uc')
    )
    op.create_index(op.f('ix_monthly_reports_id'), 'monthly_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_reports_id'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_research_topics_id'), table_name='research_topics')
    op.drop_table('research_topics')
    # ### end Alembic commands ###
