"""add attendance, calendar, service_activities

Revision ID: 32b369a79c65
Revises: 33ef3609b75d
Create Date: 2026-04-06 15:43:24.106400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b369a79c65'
down_revision: Union[str, Sequence[str], None] = '33ef3609b75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_days_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='_calendar_year_month_uc')
    )
    op.create_index(op.f('ix_working_days_calendar_id'), 'working_days_calendar', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='_attendance_emp_period_uc')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('service_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('criterion_name', sa.String(length=200), nullable=False),
    sa.Column('criterion_weight', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_activities_id'), 'service_activities', ['id'], unique=False)
    op.drop_constraint(op.f('employee_monthly_scores_employee_id_year_month_key'), 'employee_monthly_scores', type_='unique')
    op.create_unique_constraint('_emp_score_period_uc', 'employee_monthly_scores', ['employee_id', 'year', 'month'])
    op.drop_constraint(op.f('monthly_reports_lab_head_id_year_month_key'), 'monthly_reports', type_='unique')
    op.create_unique_constraint('_lab_head_period_uc', 'monthly_reports', ['lab_head_id', 'year', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_lab_head_period_uc', 'monthly_reports', type_='unique')
    op.create_unique_constraint(op.f('monthly_reports_lab_head_id_year_month_key'), 'monthly_reports', ['lab_head_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('_emp_score_period_uc', 'employee_monthly_scores', type_='unique')
    op.create_unique_constraint(op.f('employee_monthly_scores_employee_id_year_month_key'), 'employee_monthly_scores', ['employee_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_service_activities_id'), table_name='service_activities')
    op.drop_table('service_activities')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_working_days_calendar_id'), table_name='working_days_calendar')
    op.drop_table('working_days_calendar')
    # ### end Alembic commands ###
