"""unified report schema with entries and scores

Revision ID: 33ef3609b75d
Revises: 273b04b83b29
Create Date: 2026-04-06 14:58:34.848333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ef3609b75d'
down_revision: Union[str, Sequence[str], None] = '273b04b83b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_monthly_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('topic_points', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('additional_points', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('total_points', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month')
    )
    op.create_index(op.f('ix_employee_monthly_scores_id'), 'employee_monthly_scores', ['id'], unique=False)
    op.create_table('report_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_title', sa.String(length=300), nullable=True),
    sa.Column('doi_or_link', sa.String(length=300), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_reports.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_entries_id'), 'report_entries', ['id'], unique=False)
    op.add_column('monthly_reports', sa.Column('lab_head_id', sa.Integer(), nullable=False))
    op.add_column('monthly_reports', sa.Column('department', sa.String(length=200), nullable=False))
    op.add_column('monthly_reports', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('monthly_reports', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('monthly_reports', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monthly_reports', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('_user_topic_period_uc'), 'monthly_reports', type_='unique')
    op.create_unique_constraint(None, 'monthly_reports', ['lab_head_id', 'year', 'month'])
    op.drop_constraint(op.f('monthly_reports_user_id_fkey'), 'monthly_reports', type_='foreignkey')
    op.drop_constraint(op.f('monthly_reports_topic_id_fkey'), 'monthly_reports', type_='foreignkey')
    op.create_foreign_key(None, 'monthly_reports', 'users', ['lab_head_id'], ['id'])
    op.drop_column('monthly_reports', 'doi_list')
    op.drop_column('monthly_reports', 'period_year')
    op.drop_column('monthly_reports', 'additional_notes')
    op.drop_column('monthly_reports', 'additional_score')
    op.drop_column('monthly_reports', 'nir_score')
    op.drop_column('monthly_reports', 'period_month')
    op.drop_column('monthly_reports', 'publications_count')
    op.drop_column('monthly_reports', 'topic_id')
    op.drop_column('monthly_reports', 'total_score')
    op.drop_column('monthly_reports', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_reports', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('monthly_reports', sa.Column('total_score', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('monthly_reports', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('monthly_reports', sa.Column('publications_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthly_reports', sa.Column('period_month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('monthly_reports', sa.Column('nir_score', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('monthly_reports', sa.Column('additional_score', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('monthly_reports', sa.Column('additional_notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('monthly_reports', sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('monthly_reports', sa.Column('doi_list', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monthly_reports', type_='foreignkey')
    op.create_foreign_key(op.f('monthly_reports_topic_id_fkey'), 'monthly_reports', 'research_topics', ['topic_id'], ['id'])
    op.create_foreign_key(op.f('monthly_reports_user_id_fkey'), 'monthly_reports', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'monthly_reports', type_='unique')
    op.create_unique_constraint(op.f('_user_topic_period_uc'), 'monthly_reports', ['user_id', 'topic_id', 'period_year', 'period_month'], postgresql_nulls_not_distinct=False)
    op.drop_column('monthly_reports', 'approved_at')
    op.drop_column('monthly_reports', 'submitted_at')
    op.drop_column('monthly_reports', 'month')
    op.drop_column('monthly_reports', 'year')
    op.drop_column('monthly_reports', 'department')
    op.drop_column('monthly_reports', 'lab_head_id')
    op.drop_index(op.f('ix_report_entries_id'), table_name='report_entries')
    op.drop_table('report_entries')
    op.drop_index(op.f('ix_employee_monthly_scores_id'), table_name='employee_monthly_scores')
    op.drop_table('employee_monthly_scores')
    # ### end Alembic commands ###
