"""add topic participants and dates

Revision ID: 820b6bf04df6
Revises: bec3636e1ad0
Create Date: 2026-04-07 14:54:15.454003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820b6bf04df6'
down_revision: Union[str, Sequence[str], None] = 'bec3636e1ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_executors',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.add_column('research_topics', sa.Column('head_id', sa.Integer(), nullable=True))
    op.add_column('research_topics', sa.Column('responsible_id', sa.Integer(), nullable=True))
    op.add_column('research_topics', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('research_topics', sa.Column('date_end', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'research_topics', 'users', ['head_id'], ['id'])
    op.create_foreign_key(None, 'research_topics', 'users', ['responsible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_topics', type_='foreignkey')
    op.drop_constraint(None, 'research_topics', type_='foreignkey')
    op.drop_column('research_topics', 'date_end')
    op.drop_column('research_topics', 'date_start')
    op.drop_column('research_topics', 'responsible_id')
    op.drop_column('research_topics', 'head_id')
    op.drop_table('topic_executors')
    # ### end Alembic commands ###
