"""add publications and payment plans

Revision ID: ed5606e3f936
Revises: 820b6bf04df6
Create Date: 2026-04-07 16:06:34.267463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5606e3f936'
down_revision: Union[str, Sequence[str], None] = '820b6bf04df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('journal', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('protocol_date', sa.Date(), nullable=True),
    sa.Column('publication_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_table('publication_authors',
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('publication_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'employee_id', 'year', 'month', name='_plan_unique')
    )
    op.create_index(op.f('ix_publication_plans_id'), 'publication_plans', ['id'], unique=False)
    op.create_table('publication_topics',
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['research_topics.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_topics')
    op.drop_index(op.f('ix_publication_plans_id'), table_name='publication_plans')
    op.drop_table('publication_plans')
    op.drop_table('publication_authors')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
